services:
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    image: postgres:11.10
    container_name: account-management-postgres
    ports:
      - '4444:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db

  volumes:
    redis:
      driver: local
